"""Initial migration with all tables

Revision ID: 0f16fa86a069
Revises: 
Create Date: 2025-07-31 21:13:06.040169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f16fa86a069'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monday', sa.String(length=255), nullable=True),
    sa.Column('tuesday', sa.String(length=255), nullable=True),
    sa.Column('wednesday', sa.String(length=255), nullable=True),
    sa.Column('thursday', sa.String(length=255), nullable=True),
    sa.Column('friday', sa.String(length=255), nullable=True),
    sa.Column('saturday', sa.String(length=255), nullable=True),
    sa.Column('sunday', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('last_sent_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_events')
    # ### end Alembic commands ###
