"""Add new columns to weekly_events table

Revision ID: 24fd168e610e
Revises: 
Create Date: 2025-07-31 20:34:50.829249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fd168e610e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_event')
    op.drop_table('reminder')
    with op.batch_alter_table('weekly_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('last_sent_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_events', schema=None) as batch_op:
        batch_op.drop_column('last_sent_date')
        batch_op.drop_column('reminder_time')

    op.create_table('reminder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('weekly_event_id', sa.INTEGER(), nullable=False),
    sa.Column('time_offset_minutes', sa.INTEGER(), nullable=False),
    sa.Column('message_sent_this_week', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['weekly_event_id'], ['weekly_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('queue', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
