"""Initial migration

Revision ID: 54053b1572e2
Revises:
Create Date: 2025-07-31 22:11:51.433969

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54053b1572e2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bonuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("queue_type", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.String(length=5), nullable=False),
        sa.Column("duration_hours", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("time_slot", sa.String(length=5), nullable=False),
        sa.Column("queue_type", sa.String(length=50), nullable=False),
        sa.Column("booked_by", sa.String(length=100), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "booking_date", "time_slot", "queue_type", name="_booking_uc"
        ),
    )
    op.create_table(
        "weekly_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("monday", sa.String(length=255), nullable=True),
        sa.Column("tuesday", sa.String(length=255), nullable=True),
        sa.Column("wednesday", sa.String(length=255), nullable=True),
        sa.Column("thursday", sa.String(length=255), nullable=True),
        sa.Column("friday", sa.String(length=255), nullable=True),
        sa.Column("saturday", sa.String(length=255), nullable=True),
        sa.Column("sunday", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("reminder_time", sa.String(length=5), nullable=True),
        sa.Column("last_sent_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weekly_events")
    op.drop_table("bookings")
    op.drop_table("bonuses")
    # ### end Alembic commands ###
